<?php
declare(strict_types=1);

require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/csrf.php';
require_once __DIR__ . '/../includes/admin_header.php';
require_once __DIR__ . '/../includes/smtp_mailer.php';

$admin = require_admin();
$pdo = db();
$recoveryConfigPath = __DIR__ . '/../includes/recovery.local.php';
$completed = defined('RECOVERY_SETUP_COMPLETE') && (bool)constant('RECOVERY_SETUP_COMPLETE');
$errors = [];
$checks = [];

function recovery_setup_ensure_schema(PDO $pdo): void
{
    $pdo->exec(<<<'SQL'
CREATE TABLE IF NOT EXISTS `password_reset_codes` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `admin_id` int unsigned NOT NULL,
  `code_hash` varchar(255) NOT NULL,
  `request_ip_hash` char(64) NOT NULL,
  `attempts` tinyint unsigned NOT NULL DEFAULT 0,
  `expires_at` datetime NOT NULL,
  `used_at` datetime DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_password_reset_ip_time` (`request_ip_hash`,`created_at`),
  KEY `idx_password_reset_admin_active` (`admin_id`,`used_at`,`expires_at`),
  CONSTRAINT `fk_password_reset_admin` FOREIGN KEY (`admin_id`) REFERENCES `admins` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
SQL);

    $stmt = $pdo->prepare(
        'INSERT IGNORE INTO settings (setting_key, setting_value) VALUES (?, ?)'
    );
    $stmt->execute(['protected_recovery_enabled', '1']);
}

function recovery_setup_admin_password_valid(PDO $pdo, int $adminId, string $password): bool
{
    $stmt = $pdo->prepare(
        'SELECT password_hash FROM admins WHERE id = ? AND is_active = 1 LIMIT 1'
    );
    $stmt->execute([$adminId]);
    $hash = $stmt->fetchColumn();

    return $hash !== false && password_verify($password, (string)$hash);
}

function recovery_setup_config_contents(
    string $senderEmail,
    string $appPassword,
    string $protectedEmail,
    string $protectionCodeHash
): string {
    return "<?php\n"
        . "declare(strict_types=1);\n\n"
        . "/**\n"
        . " * Private Bar Tadeo password-recovery configuration.\n"
        . " * Generated by /tadeo-admin/recovery-setup.php.\n"
        . " * NEVER commit this file to GitHub.\n"
        . " */\n\n"
        . "const RECOVERY_SETUP_COMPLETE = true;\n"
        . "const SMTP_HOST = 'smtp.gmail.com';\n"
        . "const SMTP_PORT = 587;\n"
        . 'const SMTP_USERNAME = ' . var_export($senderEmail, true) . ";\n"
        . 'const SMTP_PASSWORD = ' . var_export($appPassword, true) . ";\n"
        . 'const SMTP_FROM_EMAIL = ' . var_export($senderEmail, true) . ";\n"
        . "const SMTP_FROM_NAME = 'Bar Tadeo';\n"
        . 'const PROTECTED_RECOVERY_EMAIL = ' . var_export($protectedEmail, true) . ";\n"
        . 'const PROTECTED_RECOVERY_CODE_HASH = ' . var_export($protectionCodeHash, true) . ";\n";
}

function recovery_setup_write_private_file(string $targetPath, string $contents): void
{
    if (file_exists($targetPath)) {
        throw new RuntimeException('Konfigurimi i rikuperimit ekziston tashmë dhe nuk do të mbishkruhet.');
    }

    $dir = dirname($targetPath);
    if (!is_dir($dir) || !is_writable($dir)) {
        throw new RuntimeException('Serveri nuk lejon krijimin e skedarit privat recovery.local.php.');
    }

    $tmpPath = $targetPath . '.tmp-' . bin2hex(random_bytes(6));
    $written = @file_put_contents($tmpPath, $contents, LOCK_EX);

    if ($written === false || $written !== strlen($contents)) {
        @unlink($tmpPath);
        throw new RuntimeException('Konfigurimi i rikuperimit nuk u shkrua dot në server.');
    }

    @chmod($tmpPath, 0600);

    if (file_exists($targetPath) || !@rename($tmpPath, $targetPath)) {
        @unlink($tmpPath);
        throw new RuntimeException('Konfigurimi i rikuperimit nuk u aktivizua dot në server.');
    }

    @chmod($targetPath, 0600);
}

if (!$completed && is_file($recoveryConfigPath)) {
    $errors[] = 'Ekziston një skedar recovery.local.php i papërfunduar. Për siguri, konfigurimi nuk do ta mbishkruajë.';
}

$form = [
    'sender_email' => strtolower(trim((string)($_POST['sender_email'] ?? ''))),
    'protected_email' => strtolower(trim((string)($_POST['protected_email'] ?? ''))),
    'recovery_email' => strtolower(trim((string)($_POST['recovery_email'] ?? ''))),
];

if ($_SERVER['REQUEST_METHOD'] === 'POST' && !$completed && !$errors) {
    if (!csrf_verify()) {
        $errors[] = 'Kontrolli i sigurisë dështoi. Rifresko faqen dhe provo përsëri.';
    } else {
        $currentPassword = (string)($_POST['current_password'] ?? '');
        $appPassword = str_replace(' ', '', trim((string)($_POST['app_password'] ?? '')));
        $protectionCode = trim((string)($_POST['protection_code'] ?? ''));
        $protectionCodeConfirm = trim((string)($_POST['protection_code_confirm'] ?? ''));

        if (!recovery_setup_admin_password_valid($pdo, (int)$admin['id'], $currentPassword)) {
            $errors[] = 'Password-i aktual nuk është i saktë.';
        }

        foreach (['sender_email', 'protected_email', 'recovery_email'] as $field) {
            if (!filter_var($form[$field], FILTER_VALIDATE_EMAIL)) {
                $errors[] = 'Të gjitha adresat e email-it duhet të jenë të vlefshme.';
                break;
            }
        }

        if ($form['protected_email'] !== '' && strcasecmp($form['protected_email'], $form['recovery_email']) === 0) {
            $errors[] = 'Email-i i mbrojtur dhe email-i i hyrjes/rikuperimit duhet të jenë të ndryshëm.';
        }

        if (strlen($appPassword) !== 16) {
            $errors[] = 'Google App Password duhet të ketë 16 karaktere.';
        }

        if (strlen($protectionCode) < 6) {
            $errors[] = 'Kodi privat i mbrojtjes duhet të ketë të paktën 6 karaktere.';
        } elseif ($protectionCode !== $protectionCodeConfirm) {
            $errors[] = 'Konfirmimi i kodit privat nuk përputhet.';
        }

        if (!$errors) {
            try {
                recovery_setup_ensure_schema($pdo);
                $checks[] = 'Databaza dhe tabela password_reset_codes: në rregull';

                if (!is_writable(dirname($recoveryConfigPath))) {
                    throw new RuntimeException('Dosja includes nuk lejon shkrim nga PHP.');
                }
                $checks[] = 'Ruajtja private e konfigurimit: në rregull';

                $smtpConfig = [
                    'host' => 'smtp.gmail.com',
                    'port' => 587,
                    'username' => $form['sender_email'],
                    'password' => $appPassword,
                    'from_email' => $form['sender_email'],
                    'from_name' => 'Bar Tadeo',
                ];

                $testSubject = 'Bar Tadeo - Test i rikuperimit';
                $testBody = "Ky është një email test nga konfigurimi i rikuperimit të Bar Tadeo.\n\n"
                    . "Nëse e more këtë email, lidhja Gmail SMTP, TLS dhe autentikimi funksionojnë.";

                smtp_send_text_email_with_config(
                    $smtpConfig,
                    $form['protected_email'],
                    $testSubject,
                    $testBody
                );
                $checks[] = 'Gmail SMTP/TLS, autentikimi dhe email-i i mbrojtur: në rregull';

                smtp_send_text_email_with_config(
                    $smtpConfig,
                    $form['recovery_email'],
                    $testSubject,
                    $testBody
                );
                $checks[] = 'Email-i i hyrjes/rikuperimit: në rregull';

                $protectionCodeHash = password_hash($protectionCode, PASSWORD_DEFAULT);
                if ($protectionCodeHash === false) {
                    throw new RuntimeException('Hash-i i kodit privat nuk u krijua dot.');
                }
                $checks[] = 'Kodi privat u ruajt si hash: në rregull';

                $configContents = recovery_setup_config_contents(
                    $form['sender_email'],
                    $appPassword,
                    $form['protected_email'],
                    $protectionCodeHash
                );

                $pdo->beginTransaction();
                try {
                    $stmt = $pdo->prepare(
                        'INSERT INTO settings (setting_key, setting_value) VALUES (?, ?) '
                        . 'ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)'
                    );
                    $stmt->execute(['recovery_email', $form['recovery_email']]);
                    $stmt->execute(['protected_recovery_enabled', '1']);

                    recovery_setup_write_private_file($recoveryConfigPath, $configContents);
                    $pdo->commit();
                } catch (Throwable $e) {
                    if ($pdo->inTransaction()) {
                        $pdo->rollBack();
                    }
                    if (is_file($recoveryConfigPath)) {
                        @unlink($recoveryConfigPath);
                    }
                    throw $e;
                }

                $checks[] = 'Cilësimet e rikuperimit u ruajtën: në rregull';
                $checks[] = 'Skedari privat recovery.local.php u krijua: në rregull';
                $completed = true;
            } catch (Throwable $e) {
                $errors[] = $e->getMessage();
            }
        }
    }
}
?>
<!doctype html>
<html lang="sq">
<head>
    <meta charset="utf-8">
    <title>Konfigurimi i rikuperimit | <?= e(site_bar_name()) ?> Admin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/assets/css/admin.css?v=20260512-admin-header-actions-2">
</head>
<body>
    <div class="admin-layout">
        <?php render_admin_header($admin, 'settings'); ?>

        <main>
            <h1 class="admin-title">Konfigurimi i rikuperimit</h1>
            <p class="admin-muted">
                Konfigurim njëpërdorimësh për Gmail SMTP dhe email-et e rikuperimit.
            </p>

            <?php foreach ($errors as $error): ?>
                <div class="error"><?= e($error) ?></div>
            <?php endforeach; ?>

            <?php if ($completed): ?>
                <section class="form-card">
                    <div class="msg">Konfigurimi i rikuperimit u përfundua me sukses.</div>

                    <?php foreach ($checks as $check): ?>
                        <p><?= e('✓ ' . $check) ?></p>
                    <?php endforeach; ?>

                    <p class="admin-muted">
                        Konfigurimi është i mbyllur dhe nuk mund të mbishkruajë të dhënat ekzistuese.
                        Pas testimit në faqe, kjo faqe mund të hiqet nga serveri dhe repozitori.
                    </p>

                    <a class="btn" href="/tadeo-admin/settings.php">Kthehu te Cilësimet</a>
                </section>
            <?php elseif (!$errors || !is_file($recoveryConfigPath)): ?>
                <form class="form-card" method="post" autocomplete="off">
                    <?= csrf_field() ?>

                    <label>Email-i dërgues i Gmail</label>
                    <input
                        name="sender_email"
                        type="email"
                        value="<?= e($form['sender_email']) ?>"
                        autocomplete="username"
                        required
                    >

                    <label>Google App Password</label>
                    <input
                        name="app_password"
                        type="password"
                        autocomplete="new-password"
                        inputmode="text"
                        required
                    >
                    <div class="help-text">Pranon Google App Password-in me 16 karaktere; hapësirat hiqen automatikisht.</div>

                    <label>Email-i i mbrojtur i rikuperimit</label>
                    <input
                        name="protected_email"
                        type="email"
                        value="<?= e($form['protected_email']) ?>"
                        autocomplete="off"
                        required
                    >

                    <label>Email-i i hyrjes dhe rikuperimit</label>
                    <input
                        name="recovery_email"
                        type="email"
                        value="<?= e($form['recovery_email']) ?>"
                        autocomplete="off"
                        required
                    >

                    <label>Kodi privat i mbrojtjes</label>
                    <input
                        name="protection_code"
                        type="password"
                        inputmode="numeric"
                        autocomplete="off"
                        required
                    >

                    <label>Konfirmo kodin privat</label>
                    <input
                        name="protection_code_confirm"
                        type="password"
                        inputmode="numeric"
                        autocomplete="off"
                        required
                    >

                    <label>Password-i aktual</label>
                    <input
                        name="current_password"
                        type="password"
                        autocomplete="current-password"
                        required
                    >

                    <button type="submit">Testo dhe ruaj konfigurimin</button>

                    <div class="help-text">
                        Google App Password dhe kodi privat nuk ruhen në databazë. Konfigurimi ruhet vetëm
                        në skedarin privat recovery.local.php pasi email-et e testimit të dërgohen me sukses.
                    </div>
                </form>
            <?php endif; ?>
        </main>
    </div>
</body>
</html>
